#!/bin/bash
set -euo pipefail

echo "=== Building Debian Package ==="

# Run build in Docker container
docker run --rm \
    -v "$(pwd):/build" \
    -w /build \
    rust-debtools:latest \
    bash -c '
        set -euo pipefail

        echo "Building for aarch64 (arm64)..."

        # Build the release binary
        cargo build --release --target aarch64-unknown-linux-gnu

        # Get version from Cargo.toml
        VERSION=$(grep "^version" Cargo.toml | head -1 | sed "s/.*\"\(.*\)\"/\1/")
        PACKAGE_NAME="halos-mdns-publisher"

        echo "Package: ${PACKAGE_NAME}"
        echo "Version: ${VERSION}"

        # Create package directory structure
        PKG_DIR="${PACKAGE_NAME}_${VERSION}_arm64"
        rm -rf "$PKG_DIR"
        mkdir -p "$PKG_DIR/DEBIAN"
        mkdir -p "$PKG_DIR/usr/bin"
        mkdir -p "$PKG_DIR/lib/systemd/system"

        # Copy binary
        cp target/aarch64-unknown-linux-gnu/release/halos-mdns-publisher "$PKG_DIR/usr/bin/"
        chmod 755 "$PKG_DIR/usr/bin/halos-mdns-publisher"

        # Copy systemd service
        cp debian/halos-mdns-publisher.service "$PKG_DIR/lib/systemd/system/"

        # Read debian version from changelog (generated by CI)
        if [ -f debian/changelog ]; then
            DEB_VERSION=$(head -1 debian/changelog | sed "s/.*(\(.*\)).*/\1/")
        else
            DEB_VERSION="${VERSION}-1"
        fi

        # Create control file
        cat > "$PKG_DIR/DEBIAN/control" << EOF
Package: ${PACKAGE_NAME}
Version: ${DEB_VERSION}
Architecture: arm64
Maintainer: Hat Labs Ltd <info@hatlabs.fi>
Depends: avahi-daemon, avahi-utils
Recommends: docker.io | docker-ce
Conflicts: halos-mdns-publisher-container
Replaces: halos-mdns-publisher-container
Description: HaLOS mDNS subdomain publisher
 Native systemd service that advertises container subdomains via mDNS.
 Monitors Docker containers for the halos.subdomain label and uses
 avahi-publish to advertise the corresponding subdomains.
EOF

        # Create postinst script
        cat > "$PKG_DIR/DEBIAN/postinst" << "POSTINST"
#!/bin/sh
set -e

case "$1" in
    configure)
        # Enable and start the service
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
            systemctl enable halos-mdns-publisher.service
            systemctl start halos-mdns-publisher.service || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
POSTINST
        chmod 755 "$PKG_DIR/DEBIAN/postinst"

        # Create postrm script
        cat > "$PKG_DIR/DEBIAN/postrm" << "POSTRM"
#!/bin/sh
set -e

case "$1" in
    purge|remove)
        # Stop and disable the service if it is running
        if [ -d /run/systemd/system ]; then
            systemctl stop halos-mdns-publisher.service 2>/dev/null || true
            systemctl disable halos-mdns-publisher.service 2>/dev/null || true
            systemctl daemon-reload
        fi
        ;;
esac

#DEBHELPER#

exit 0
POSTRM
        chmod 755 "$PKG_DIR/DEBIAN/postrm"

        # Build the package
        dpkg-deb --build "$PKG_DIR"

        # Rename to standard format
        mv "${PKG_DIR}.deb" "${PACKAGE_NAME}_${DEB_VERSION}_arm64.deb"

        echo "=== Package built successfully ==="
        ls -la *.deb
    '

# Package is already in workspace root (Docker volume mount)
# Just verify it exists
echo "=== Build complete ==="
ls -la *.deb
