#!/bin/bash
set -euo pipefail

echo "=== Building Debian Package ==="

# Run build in Docker container
docker run --rm \
    -v "$(pwd):/build" \
    -w /build \
    rust-debtools:latest \
    bash -c '
        set -euo pipefail

        echo "Building for aarch64 (arm64)..."

        # Build the release binary
        cargo build --release --target aarch64-unknown-linux-gnu

        # Get version from Cargo.toml
        VERSION=$(grep "^version" Cargo.toml | head -1 | sed "s/.*\"\(.*\)\"/\1/")
        PACKAGE_NAME="halos-mdns-publisher"

        echo "Package: ${PACKAGE_NAME}"
        echo "Version: ${VERSION}"

        # Create package directory structure
        PKG_DIR="${PACKAGE_NAME}_${VERSION}_arm64"
        rm -rf "$PKG_DIR"
        mkdir -p "$PKG_DIR/DEBIAN"
        mkdir -p "$PKG_DIR/usr/bin"
        mkdir -p "$PKG_DIR/lib/systemd/system"
        mkdir -p "$PKG_DIR/etc"

        # Copy binary
        cp target/aarch64-unknown-linux-gnu/release/halos-mdns-publisher "$PKG_DIR/usr/bin/"
        chmod 755 "$PKG_DIR/usr/bin/halos-mdns-publisher"

        # Copy systemd service
        cp debian/halos-mdns-publisher.service "$PKG_DIR/lib/systemd/system/"

        # Copy mdns.allow if it exists
        if [ -f debian/mdns.allow ]; then
            cp debian/mdns.allow "$PKG_DIR/etc/"
        fi

        # Read debian version from changelog (generated by CI)
        if [ -f debian/changelog ]; then
            DEB_VERSION=$(head -1 debian/changelog | sed "s/.*(\(.*\)).*/\1/")
        else
            DEB_VERSION="${VERSION}-1"
        fi

        # Generate control file from debian/control template
        # Extract fields and format for binary package
        {
            echo "Package: ${PACKAGE_NAME}"
            echo "Version: ${DEB_VERSION}"
            echo "Architecture: arm64"
            grep "^Maintainer:" debian/control
            # Extract Depends, removing template variables
            DEPENDS=$(grep "^Depends:" debian/control | sed "s/\${[^}]*}, *//g" | sed "s/, *\${[^}]*}//g")
            echo "$DEPENDS"
            grep "^Recommends:" debian/control || true
            grep "^Conflicts:" debian/control || true
            grep "^Replaces:" debian/control || true
            # Extract description (everything from Description: to end of file in Package stanza)
            sed -n "/^Description:/,/^$/p" debian/control | head -n -1
        } > "$PKG_DIR/DEBIAN/control"

        # Copy maintainer scripts from debian/ directory
        cp debian/postinst "$PKG_DIR/DEBIAN/postinst"
        chmod 755 "$PKG_DIR/DEBIAN/postinst"

        cp debian/postrm "$PKG_DIR/DEBIAN/postrm"
        chmod 755 "$PKG_DIR/DEBIAN/postrm"

        # Build the package
        dpkg-deb --build "$PKG_DIR"

        # Rename to standard format
        mv "${PKG_DIR}.deb" "${PACKAGE_NAME}_${DEB_VERSION}_arm64.deb"

        echo "=== Package built successfully ==="
        ls -la *.deb
    '

# Package is already in workspace root (Docker volume mount)
# Just verify it exists
echo "=== Build complete ==="
ls -la *.deb
