name: 'Check Version Consistency'
description: 'Verify VERSION file matches Cargo.toml version'

runs:
  using: 'composite'
  steps:
    - name: Check version consistency
      shell: bash
      run: |
        set -e

        # Read canonical version from VERSION file
        if [ ! -f "VERSION" ]; then
          echo "VERSION file not found"
          exit 1
        fi
        VERSION_FILE=$(cat VERSION | tr -d '[:space:]')
        echo "VERSION file: $VERSION_FILE"

        # Extract version from Cargo.toml
        CARGO_VERSION=$(grep -m1 '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
        echo "Cargo.toml:   $CARGO_VERSION"

        # Compare
        if [ "$VERSION_FILE" != "$CARGO_VERSION" ]; then
          echo ""
          echo "Version mismatch detected!"
          echo "  VERSION file: $VERSION_FILE"
          echo "  Cargo.toml:   $CARGO_VERSION"
          echo ""
          echo "Use './run bumpversion [patch|minor|major]' to update versions consistently."
          exit 1
        fi

        echo ""
        echo "Version check passed: $VERSION_FILE"
